/* C# includes a set of preprocessor directives that are mainly used for
conditional compilation. */

#define Chapter26 // conditional compilation symbols

using static System.Console;

namespace Preprocessors
{
    class Program
    {
        static void Main()
        {
            WriteLine("--- Preprocessor Syntax ---");

#line 10 "Program.cs" // set line number and file name
            WriteLine("#line 10 \"Program.cs\"");

            WriteLine("--- Conditional Compilation ---");

#if Chapter26
            Console.WriteLine("Chapter 26 is defined");
#else
                Console.WriteLine("Chapter 26 is not defined");
#endif

            WriteLine("--- Diagnostic Directives ---");

#if CsharpLabs // error directive
#error CsharpLabs is undefined 
#endif
            Console.WriteLine("#error directive example");

#if CsharpLabs2 // warning directive
#warning CsharpLabs2 is undefined
#endif
            Console.WriteLine("#warning directive example");

            WriteLine("--- Line Directive ---");

#line 96 "AnotherFile.cs"
#warning JUST WARNING EXAMPLE Actual Warning generated by Program.cs on line 42

            WriteLine("--- Region Directives ---");

            #region MyCodeHeare
            WriteLine("You can define regions of code that can be collapsed in an outline using the following two preprocessor directives");
            #endregion
        }
    }
}
